# Generated by Django 5.1 on 2024-10-26 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favoritos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritos',
            old_name='nome',
            new_name='nombre',
        ),
    ]
